# -*- coding: utf-8 -*-
"""OpenAIexemplo1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1asNgp6b3gLzBoHljS_7qe3hy0KV50TD6
"""

!pip3 install --upgrade openai

#EXEMPLO OK
import openai
openai.api_key = "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"
MODEL = "gpt-3.5-turbo"

CONTENT = "Pesquise inovações"
response = openai.ChatCompletion.create(model=MODEL, messages=[{"role": "user", "content": CONTENT}])
print(response.choices[0].message.content)

from google.colab import drive
drive.mount('/content/drive')

# Note: you need to be using OpenAI Python v0.27.0 for the code below to work
# https://platform.openai.com/docs/guides/speech-to-text/quickstart
import openai
audio_file= open("/content/drive/MyDrive/sample-3.mp3", "rb")
transcript = openai.Audio.transcribe("whisper-1", audio_file)
print(transcript)

!pip install gTTS

# Import the required module for text
# to speech conversion
from gtts import gTTS

# This module is imported so that we can
# play the converted audio
import os

# The text that you want to convert to audio
mytext = 'Vida, eu te amo.'

# Language in which you want to convert
language = 'pt'

# Passing the text and language to the engine,
# here we have marked slow=False. Which tells
# the module that the converted audio should
# have a high speed
myobj = gTTS(text=mytext, lang=language, slow=False)

# Saving the converted audio in a mp3 file named
# welcome
myobj.save("TesteText2Speech.mp3")

# Playing the converted file
os.system("mpg321 welcome.mp3")

import openai
audio_file= open("/content/TesteText2Speech.mp3", "rb")
transcript = openai.Audio.transcribe("whisper-1", audio_file)
print(transcript)

"""# Nova seção

# Nova seção
"""

import openai

parameters = {
    "deployment_id"="gpt-4",
    #"engine": "gpt-4",
    "temperature": 0.2,
    "max_tokens": 256,
    "top_p": 0.95,
}

chat = openai.ChatCompletion.create(
    messages=[
      {"role": "system", "content": "My name is Miles. You are an astronomer, knowledgeable about the solar system."},
      {"role": "user", "name":"example_user", "content": "How many planets are there in the solar system?"}
      ],
    **parameters
)

response = chat['choices'][0]['message']['content']

print(f"Response from Azure OpenAI Model: {response.text}")

